-- Insert records into DEPT table
INSERT INTO DEPT (DEPTCODE, DEPTNAME) VALUES (101, 'IT');
INSERT INTO DEPT (DEPTCODE, DEPTNAME) VALUES (102, 'HR');
INSERT INTO DEPT (DEPTCODE, DEPTNAME) VALUES (103, 'Finance');
