CREATE TABLE EMP (
    EMPCODE NUMBER NOT NULL CONSTRAINT emp_pk PRIMARY KEY,
    DEPTCODE NUMBER,
    EMPNAME VARCHAR2(25),
    JOB VARCHAR2(10),
    SAL NUMBER,
    HIREDATE DATE,
    PHONENUMBER NUMBER
);